In [24]:
import cv2

In [26]:
im_g=cv2.imread("smallgray.png",0)   
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
ims = numpy.hstack((im_g, im_g))  #hstack to concatenate two arrays horizontally; Taking the arguments as tuples

In [30]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
ims = numpy.vstack((im_g, im_g,im_g))  #hstack to concatenate two arrays vertically

In [39]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [46]:
im_s = numpy.vsplit(im_g,3)

In [49]:
im_s

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]

In [51]:
im_s = numpy.hsplit(im_g,5)

In [53]:
im_s

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [56]:
type(im_s)  #python list

list

In [57]:
im_s[0]

array([[187],
       [198],
       [209]], dtype=uint8)